apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dom-froge-ai-react-app-ingress
  namespace: dom-froge-ai   
spec:
  ingressClassName: nginx
  rules:
  - host: dom-froge-ai-react-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dom-froge-ai-react-app
            port:
              number: 8099