apiVersion: v1
kind: Service
metadata:
  name: domforgeai-service
  labels:
    app: domforgeai
spec:
  type: ClusterIP
  selector:
    app: domforgeai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
