apiVersion: v1
kind: Service
metadata:
  name: dom-froge-ai-react-app
  namespace: dom-froge-ai   
  labels:
    app: dom-froge-ai-react-app
spec:
  type: ClusterIP
  selector:
    app: dom-froge-ai-react-app
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
